/* eslint-disable */
// Generated by Wrangler by running `wrangler types --config=server/wrangler.jsonc --include-runtime=false --env-interface=CloudEnv server/worker-configuration.d.ts` (hash: 0e8f0a0c3eeda03aeaab8bc7b6f687c8)
interface __BaseEnv_CloudEnv {
	DB: D1Database;
	REQUEST_LIMIT: RateLimit;
	WRITE_LIMIT: RateLimit;
	ALLOWED_ORIGINS: "https://ctrlcctrlvisthebest.github.io,http://127.0.0.1:4173,http://localhost:4173";
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker");
	}
	interface Env extends __BaseEnv_CloudEnv {}
}
interface CloudEnv extends __BaseEnv_CloudEnv {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
	[Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
	interface ProcessEnv extends StringifyValues<Pick<Cloudflare.Env, "ALLOWED_ORIGINS">> {}
}
